#!/usr/bin/perl

$h='/usr/include/X11/keysymdef.h';

open($F,'<',$h)||die $!;
print "# generated by $0 from $h
const struct ks2unicode {KeySym ks; unsigned short u;} ks2u[]={
";
while(defined(my $s=<$F>)){
(@a=$s=~/^\#define XK_([a-zA-Z_0-9]+)\s+0x([0-9a-f]+)\s*\/\* U+([0-9A-F]{4,6}) (.*) \*\/\s*$/) ||
(@a=$s=~/^\#define XK_([a-zA-Z_0-9]+)\s+0x([0-9a-f]+)\s*\/\*\(U+([0-9A-F]{4,6}) (.*)\)\*\/\s*$/)||
(@a=$s=~/^\#define XK_([a-zA-Z_0-9]+)\s+0x([0-9a-f]+)\s*(\/\*\s*(.*)\s*\*\/)?\s*$/)||next;

(($u)=$a[2]=~/\s+U\+([A-Z0-9]{4})\s+/) || next;
print "{0x$a[1],0x$u},\n";
}
print "{0,0}\n};\n";